### ISSUE TITLE
Quick init using umd module

### ISSUE THREAD

**Issue by gr0kchain** [liquality/chainify#73]
```var bitcoin = new ChainAbstractionLayer.Client("bitcoin://user:pass@localhost:18443/")```

gives me the following error 

```javascript
{
    message: "bitcoin.BitcoinRPCProvider not found",
    name: "ProviderNotFoundError",
    stack: "ProviderNotFoundError: bitcoin.BitcoinRPCProvider …t/index.umd.js:17:102108)↵    at <anonymous>:1:16"
}
```

**Comment by harshjv** [comment]
Nice catch! `lodash.get` behaving differently in the prod build. Same works fine in dev build.
