### ISSUE TITLE
Need Bitcoin Wallet Provider that doesn't require ledger

### ISSUE THREAD

**Issue by matthewjablack** [liquality/chainify#84]
Currently everything in CAL relies on ledger for signing, to generating transactions, on bitcoin. It would be great to be able to do this directly by interacting with the bitcoin node. 

Essentially there needs to be a Bitcoin Wallet Provider and Bitcoin Swap Provider

**Comment by matthewjablack** [comment]
https://github.com/liquality/chainabstractionlayer/pull/76 was created, but relies on `bitcoinjs-lib`

Use this branch (`bitcoinjs-lib-provider`) while waiting for https://github.com/liquality/chainabstractionlayer/pull/75

**Comment by matthewjablack** [comment]
WIP https://github.com/liquality/chainabstractionlayer/pull/75 create a Bitcoin Wallet Provider. Problem with generating swap transactions.

**Comment by monokh** [comment]
The node providers now handle this.
