### ISSUE TITLE
Issue with index for transaction being signed

### ISSUE THREAD

**Issue by gr0kchain** [liquality/chainify#97]
Signing here should be 0 and not based on the previous tx's vin.index 

https://github.com/liquality/chainabstractionlayer/blob/775fb90708b2a10ce5336231e33618680ae6f29e/src/providers/bitcoin/BitcoinJsLibSwapProvider.js#L111

**Comment by matthewjablack** [comment]
`BitcoinJsLibSwapProvider.js` removed in https://github.com/liquality/chainabstractionlayer/pull/194
